### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [Caballero77/ForKottans#4]
Pass "50000000000006114" to `GetCreditCardVendor` method
Expected result: "Unknown" (invalid number)
Actual result: "Maestro"

**Comment by Caballero77** [comment]
I have one question. What issuer identification number for the correct Maestro?Wikipedia says one thing, but obviously not correct.
Other sources also provide information, but everyone is different.
So I do not understand what actually issuer identification number in Maestro.

**Comment by intrueder** [comment]
IIN range for Maestro according to wiki: 50, 56-69
But this number _does not pass Luhn validation_
